import type { LeadResult } from "@/components/agents/lead-gen/LeadResultsTable";

const MOCK_LEADS: Omit<LeadResult, "id" | "status" | "source">[] = [
  // Post Supervisors
  { contact_name: "Tyler Huang", job_title: "Post Production Supervisor", company: "Wattpad Studios", location: "Los Angeles, CA, United States", linkedin_url: "linkedin.com/in/tyler-huang-post", email: "", company_size: "50-200", vertical: "Vertical Drama", summary: "Supervises post for Wattpad's entire vertical drama slate — 3 concurrent productions, 30+ eps/season. Evaluating AI tools to speed up stylization pass.", fit_score: 94, fit_reason: "Manages multi-episode vertical drama pipeline with recurring stylization needs. Decision-maker for tooling.", pain_points: ["Manual per-episode style consistency", "Tight turnaround on 30-ep seasons"], recent_signals: ["Posted about AI post-production tools on LinkedIn", "Attended NAB 2026"] },
  { contact_name: "Ama Asante-Boateng", job_title: "Post Supervisor", company: "Channel 4 Indie", location: "London, United Kingdom", linkedin_url: "linkedin.com/in/ama-asante-post", email: "", company_size: "10-50", vertical: "Vertical Drama", summary: "Runs post for Channel 4's vertical drama output. Manages a team of 4 editors and 2 colorists. Active in BAFTA Crew community.", fit_score: 88, fit_reason: "Post supervisor with team budget, controls tooling decisions for vertical drama unit.", pain_points: ["Inconsistent grading across episodes", "Colorist availability bottlenecks"], recent_signals: ["BAFTA Crew post about vertical format challenges", "Followed Mago on LinkedIn"] },
  { contact_name: "Elif Öztürk", job_title: "Post Production Supervisor", company: "BluTV", location: "Istanbul, Turkey", linkedin_url: "linkedin.com/in/elif-ozturk-post", email: "", company_size: "50-200", vertical: "Vertical Drama", summary: "Post supervisor at Turkey's largest streaming platform. Manages 30-episode vertical drama seasons. Vocal about batch processing needs in industry panels.", fit_score: 92, fit_reason: "High-volume episodic pipeline, platform-level budget, direct AI tool purchase authority.", pain_points: ["Batch stylization across 30 episodes", "Style transfer consistency between directors"], recent_signals: ["Spoke at Istanbul Film Forum on AI in post", "Hiring VFX pipeline TD"] },
  { contact_name: "Lucía Fernández Ortiz", job_title: "Supervisora de Post Producción", company: "Banijay Iberia", location: "Madrid, Spain", linkedin_url: "linkedin.com/in/lucia-fernandez-post", email: "", company_size: "200-500", vertical: "Vertical Drama", summary: "Post supervisor at Banijay Iberia overseeing vertical drama output for Atresplayer and Movistar+. Manages two simultaneous productions.", fit_score: 86, fit_reason: "Enterprise-adjacent studio with multi-platform vertical drama output. Tooling decisions at supervisor level.", pain_points: ["Look consistency across 2 simultaneous productions", "Delivery deadlines for multiple platforms"], recent_signals: ["Published article on vertical drama workflow on LinkedIn"] },
  { contact_name: "Léa Moreau", job_title: "Post Supervisor", company: "Brut Media", location: "Paris, France", linkedin_url: "linkedin.com/in/lea-moreau-post", email: "", company_size: "50-200", vertical: "Vertical Drama", summary: "Supervises post at Brut, one of France's leading vertical-first media companies. Manages 3 concurrent vertical drama productions with social-first delivery.", fit_score: 91, fit_reason: "Vertical-first studio, high episode volume, digital delivery — exact use case for Mago.", pain_points: ["Fast turnaround for social delivery", "Style guides hard to enforce across multiple editors"], recent_signals: ["Posted about AI video tools on Twitter/X", "Attending Canneseries 2026"] },
  { contact_name: "Vasyl Bondarenko", job_title: "Post Production Supervisor", company: "Studio Kvartal 95", location: "Kyiv, Ukraine", linkedin_url: "linkedin.com/in/vasyl-bondarenko", email: "", company_size: "50-200", vertical: "Vertical Drama", summary: "Post supervisor at Ukraine's leading entertainment studio. Manages vertical drama productions distributed across European streaming platforms.", fit_score: 83, fit_reason: "Active studio with vertical drama output, cost-conscious market = high ROI for affordable AI tools.", pain_points: ["Limited access to expensive Western VFX tools", "Maintaining quality under cost pressure"], recent_signals: ["Presented at Kyiv MediaForum", "Studio announced 2026 vertical drama slate"] },

  // Lead Editors
  { contact_name: "Priya Nair", job_title: "Lead Editor", company: "WEBTOON Entertainment", location: "Los Angeles, CA, United States", linkedin_url: "linkedin.com/in/priya-nair-editor", email: "", company_size: "50-200", vertical: "Vertical Drama", summary: "Lead editor at WEBTOON's vertical drama division. Manages a team of 3 editors. Posted about AI in post-production on LinkedIn in March 2026.", fit_score: 82, fit_reason: "Leads editing team on vertical drama, influences tooling adoption.", pain_points: ["Style consistency across episode team", "Speed of stylization review rounds"], recent_signals: ["LinkedIn post: 'AI is changing how we approach vertical drama post'"] },
  { contact_name: "Niamh O'Brien", job_title: "Lead Editor", company: "Fremantle UK", location: "London, United Kingdom", linkedin_url: "linkedin.com/in/niamh-obrien-editor", email: "", company_size: "200-500", vertical: "Vertical Drama", summary: "Lead editor at Fremantle UK's vertical drama label. Cuts 60-90s episodes for BBC iPlayer and Channel 4. Recently complained publicly about tool fragmentation.", fit_score: 80, fit_reason: "High-volume episodic editor with influence on tooling, vocal about pain points.", pain_points: ["Tool fragmentation in post pipeline", "Getting consistent grade without full-time colorist"] },
  { contact_name: "Mert Demir", job_title: "Kurgu Şefi (Lead Editor)", company: "Gain TV", location: "Istanbul, Turkey", linkedin_url: "linkedin.com/in/mert-demir-editor", email: "", company_size: "50-200", vertical: "Vertical Drama", summary: "Lead editor at Gain TV, Turkey's vertical drama platform. Cuts multi-episode series in Premiere Pro. Active in Turkish editors community on Facebook.", fit_score: 78, fit_reason: "Platform-level lead editor with steady episodic volume and peer influence.", pain_points: ["Manual color pass on each episode", "Episode look drifts between seasons"], recent_signals: ["Active in Turkey Editors Facebook group", "Posted BTS of vertical drama edit workflow"] },
  { contact_name: "Carmen Ruiz Ibáñez", job_title: "Lead Editor", company: "Movistar+", location: "Madrid, Spain", linkedin_url: "linkedin.com/in/carmen-ruiz-editor", email: "", company_size: "200-500", vertical: "Vertical Drama", summary: "Lead editor for Movistar+'s vertical drama content. Manages editorial workflow across Madrid-based productions. Speaker at Madrid Film Festival editing panel.", fit_score: 77, fit_reason: "Major Spanish platform editor with vertical drama specialisation.", pain_points: ["Maintaining visual consistency with multiple DPs", "Quick-turn delivery for social"] },
  { contact_name: "Sophie Mercier", job_title: "Cheffe Monteuse", company: "Canal+ Vertical", location: "Paris, France", linkedin_url: "linkedin.com/in/sophie-mercier-editor", email: "", company_size: "50-200", vertical: "Vertical Drama", summary: "Head editor at Canal+ vertical drama unit. Technical evaluator for post tooling. Has tested multiple AI tools and blogs about them on Substack.", fit_score: 85, fit_reason: "Technical evaluator role, high episode output, vocal about AI tools.", pain_points: ["AI tools lack frame-accurate vertical format support", "Render speed for social delivery"], recent_signals: ["Substack post reviewing AI video tools", "Followed Mago on LinkedIn"] },
  { contact_name: "Anastasiia Shevchenko", job_title: "Lead Editor", company: "Megogo", location: "Kyiv, Ukraine", linkedin_url: "linkedin.com/in/anastasiia-shevchenko", email: "", company_size: "50-200", vertical: "Vertical Drama", summary: "Lead editor at Megogo, Ukraine's largest streaming platform. Edits vertical drama series for 12M+ subscriber base. Budget-conscious but volume-driven.", fit_score: 79, fit_reason: "High-volume platform editor — strong volume ROI for batch processing.", pain_points: ["Manual export pipeline for 25-ep seasons", "Stylization overhead adds days to delivery"] },

  // Colorists
  { contact_name: "Celine Johansson", job_title: "Senior Colorist", company: "Freelance", location: "Los Angeles, CA, United States", linkedin_url: "linkedin.com/in/celine-johansson-color", email: "", company_size: "1-10", vertical: "Post Production", summary: "Freelance senior colorist in LA working exclusively on vertical drama. Grades 8+ productions per year on DaVinci Resolve. Active in Colorist Society International.", fit_score: 89, fit_reason: "High-volume freelance colorist, early adopter profile, self-serve ideal customer.", pain_points: ["Client expects AI-assisted grade speed without losing quality", "No budget for full Resolve Studio on every gig"], recent_signals: ["CSI member, active in colorist Discord", "Posted about AI grading tools on IG"] },
  { contact_name: "Liam Barrett", job_title: "Colorist", company: "Goldcrest Post", location: "London, United Kingdom", linkedin_url: "linkedin.com/in/liam-barrett-color", email: "", company_size: "50-200", vertical: "Post Production", summary: "Colorist at Goldcrest Post, London's leading post house. Works on UK vertical drama productions for BBC and Channel 4. Attended VES UK chapter last month.", fit_score: 84, fit_reason: "Facility colorist with vertical drama specialty — influences tool adoption at studio level.", pain_points: ["Batch grading across 20-ep season is slow", "Client expectation creep on AI stylization"] },
  { contact_name: "Zeynep Arslan", job_title: "Senior Colorist", company: "Netflix Turkey", location: "Istanbul, Turkey", linkedin_url: "linkedin.com/in/zeynep-arslan-color", email: "", company_size: "50-200", vertical: "Post Production", summary: "Senior colorist at Netflix Turkey. Grades local vertical drama content. Has 4.2k followers on Instagram where she posts grading tutorials.", fit_score: 87, fit_reason: "Platform colorist with social reach — potential Mago advocate and self-serve user.", pain_points: ["Style transfer for season-over-season consistency", "Turnaround speed for digital-first delivery"], recent_signals: ["Instagram tutorial on vertical frame grading went viral (42k views)"] },
  { contact_name: "Alejandro Moreno Díaz", job_title: "Colorista", company: "Freelance", location: "Madrid, Spain", linkedin_url: "linkedin.com/in/alejandro-moreno-color", email: "", company_size: "1-10", vertical: "Post Production", summary: "Freelance colorist in Madrid. Works on vertical drama for Atresplayer, Movistar+, and independent studios. Runs a grading workshop at Madrid Film School.", fit_score: 88, fit_reason: "Freelance, high-volume, educator — early adopter and community multiplier.", pain_points: ["Manual pass per episode not scalable as workload grows", "Clients requesting AI looks without briefing"], recent_signals: ["Workshop on AI in post at Madrid Film School", "Active in Spain colorist WhatsApp group"] },
  { contact_name: "Antoine Dupont", job_title: "Coloriste", company: "TF1+ Studio", location: "Paris, France", linkedin_url: "linkedin.com/in/antoine-dupont-color", email: "", company_size: "50-200", vertical: "Post Production", summary: "Colorist at TF1+ working on their vertical drama slate. Previously freelance for Brut. Has reviewed AI grading tools on his LinkedIn newsletter.", fit_score: 82, fit_reason: "Platform colorist with influencer reach in French post community.", pain_points: ["Replicating grade consistency across episodes from different shoots", "AI tools not trained on French vertical drama aesthetic"] },
  { contact_name: "Olena Kovalenko", job_title: "Colorist", company: "Freelance", location: "Kyiv, Ukraine", linkedin_url: "linkedin.com/in/olena-kovalenko-color", email: "", company_size: "1-10", vertical: "Post Production", summary: "Freelance colorist in Kyiv. Works on 5-6 vertical drama productions per year for Ukrainian and European studios. Member of Kyiv Post Production Guild.", fit_score: 80, fit_reason: "Freelance, high episodic volume, cost-sensitive — high ROI potential with self-serve plan.", pain_points: ["Limited access to premium tools on freelance rates", "Batch grading 20+ episodes without assistant colorist"] },

  // VFX Freelancers
  { contact_name: "Marcus Webb", job_title: "VFX Lead", company: "Studio71", location: "Los Angeles, CA, United States", linkedin_url: "linkedin.com/in/marcus-webb-vfx", email: "", company_size: "50-200", vertical: "VFX", summary: "VFX Lead at Studio71 overseeing AI-driven stylization for their vertical drama slate. Evaluating tools to replace manual compositing on high-volume episodic work.", fit_score: 90, fit_reason: "Decision-maker for VFX tooling on high-volume vertical drama. Actively evaluating AI tools.", pain_points: ["Manual comp on 30-ep seasons unsustainable", "Style consistency between VFX shots from different artists"], recent_signals: ["Posted VFX breakdown of vertical drama shot on LinkedIn", "Attended SIGGRAPH 2025"] },
  { contact_name: "Josh Kimani", job_title: "VFX Compositor", company: "Framestore", location: "London, United Kingdom", linkedin_url: "linkedin.com/in/josh-kimani-vfx", email: "", company_size: "200-500", vertical: "VFX", summary: "VFX compositor at Framestore. Side projects on vertical drama for indie studios. Active in VES UK chapter. Posted about AI compositing workflows on Twitter/X.", fit_score: 76, fit_reason: "Facility compositor with active side projects in vertical drama — self-serve candidate.", pain_points: ["Compositing overhead on fast-turnaround vertical drama", "Limited AI tools with vertical frame support"] },
  { contact_name: "Kemal Yılmaz", job_title: "VFX Supervisor", company: "BluTV", location: "Istanbul, Turkey", linkedin_url: "linkedin.com/in/kemal-yilmaz-vfx", email: "", company_size: "50-200", vertical: "VFX", summary: "VFX Supervisor at BluTV. Oversees AI pipeline evaluation for vertical drama. Has implemented 2 AI tools in the last year. Technical decision-maker.", fit_score: 91, fit_reason: "Technical supervisor actively building AI VFX pipeline — high probability of adoption.", pain_points: ["No off-the-shelf AI tool handles vertical frame natively", "Rendering costs for per-episode stylization"], recent_signals: ["Presented AI pipeline at TRT Future Media Summit", "Hired pipeline TD for AI integration"] },
  { contact_name: "Pablo García Núñez", job_title: "VFX Artist & Compositor", company: "Freelance", location: "Madrid, Spain", linkedin_url: "linkedin.com/in/pablo-garcia-vfx", email: "", company_size: "1-10", vertical: "VFX", summary: "Freelance VFX artist in Madrid. Works on Movistar+ and indie vertical drama productions. Part of Madrid VFX collective with 80+ members. Runs VFX tutorials on YouTube.", fit_score: 84, fit_reason: "Freelance multiplier — YouTube educator with VFX community reach in Spain.", pain_points: ["Client budgets too low for traditional VFX pipeline", "Needs AI to deliver studio quality solo"], recent_signals: ["YouTube tutorial on AI VFX for vertical drama (18k views)", "Madrid VFX collective organiser"] },
  { contact_name: "Théo Blanchard", job_title: "Compositeur VFX", company: "Freelance", location: "Paris, France", linkedin_url: "linkedin.com/in/theo-blanchard-vfx", email: "", company_size: "1-10", vertical: "VFX", summary: "Freelance VFX compositor in Paris. Works on Canal+ and Brut vertical drama. Member of AFC. Shared Mago's Instagram post with positive comment.", fit_score: 81, fit_reason: "Freelance, already engaged with Mago content, vertical drama niche match.", pain_points: ["Slow render on complex stylization for tight turnarounds", "Inconsistent AI tool quality for vertical format"], recent_signals: ["Shared Mago Instagram post", "AFC community member"] },
  { contact_name: "Dmytro Petrenko", job_title: "VFX Lead", company: "Freelance", location: "Kyiv, Ukraine", linkedin_url: "linkedin.com/in/dmytro-petrenko-vfx", email: "", company_size: "1-10", vertical: "VFX", summary: "Freelance VFX lead in Kyiv. Works on Ukrainian and Polish vertical drama co-productions. Previously tried Runway ML but found it lacking for episodic consistency.", fit_score: 83, fit_reason: "Evaluated competitors, open to better solution — episodic consistency is a known pain.", pain_points: ["Runway ML lacks frame consistency for episodic work", "No tool supports batch vertical processing"], recent_signals: ["Posted critical review of Runway ML for episodic VFX on LinkedIn"] },

  // Directors
  { contact_name: "Jake Torres", job_title: "Director / DGA Member", company: "Freelance", location: "Los Angeles, CA, United States", linkedin_url: "linkedin.com/in/jake-torres-director", email: "", company_size: "1-10", vertical: "Film & TV", summary: "DGA director with 6 vertical drama series. Collaborates with post team on visual style from pre-production. Vocal advocate for AI tools that preserve directorial intent.", fit_score: 78, fit_reason: "Director with post influence, vocal AI advocate, self-serve candidate.", pain_points: ["AI stylization doesn't always match directorial vision", "Hard to brief colorist on AI-generated look"], recent_signals: ["Panel at LA WebFest on AI-assisted vertical drama direction"] },
  { contact_name: "Freya Carlson", job_title: "Director", company: "Fremantle UK", location: "London, United Kingdom", linkedin_url: "linkedin.com/in/freya-carlson-director", email: "", company_size: "200-500", vertical: "Film & TV", summary: "Director at Fremantle UK vertical drama label. Directs 4 episodes per season. Has built personal brand around consistent visual style across her vertical drama work.", fit_score: 75, fit_reason: "Director focused on consistent visual language — natural fit for Mago style transfer.", pain_points: ["Maintaining visual consistency when colorist changes episode to episode", "Director-to-post handoff on style intent is lossy"] },
  { contact_name: "Cem Başar", job_title: "Yönetmen (Director)", company: "O3 Medya", location: "Istanbul, Turkey", linkedin_url: "linkedin.com/in/cem-basar-director", email: "", company_size: "10-50", vertical: "Film & TV", summary: "Director at O3 Medya, Istanbul's largest vertical drama studio. Directed 5 series across BluTV and TRT. Frequent speaker at Istanbul vertical drama industry events.", fit_score: 82, fit_reason: "High-profile director with platform relationships — ideal advocate in Turkish market.", pain_points: ["Each production has different post team, loses visual signature", "AI tools disrupt editorial intent if not guided"], recent_signals: ["Keynote at Istanbul Vertical Drama Summit"] },
  { contact_name: "Isabel Santos Vega", job_title: "Directora", company: "Fremantle Spain", location: "Madrid, Spain", linkedin_url: "linkedin.com/in/isabel-santos-director", email: "", company_size: "200-500", vertical: "Film & TV", summary: "Director at Fremantle Spain. Runs two concurrent vertical drama productions for Atresplayer and Amazon Prime Video Spain. Has a recognizable visual aesthetic.", fit_score: 74, fit_reason: "Multi-production director with budget influence at studio level.", pain_points: ["Two concurrent productions mean visual style gets diluted", "No standardised AI tool across Fremantle Spain productions"] },
  { contact_name: "Amélie Rousseau", job_title: "Réalisatrice", company: "Brut Media", location: "Paris, France", linkedin_url: "linkedin.com/in/amelie-rousseau-director", email: "", company_size: "50-200", vertical: "Film & TV", summary: "Director at Brut Media with a highly distinctive visual style and 28k Instagram followers. Documents her filmmaking process publicly and is vocal about AI in post.", fit_score: 80, fit_reason: "Influential director with social reach and visual identity focus — Mago advocate potential.", pain_points: ["Post team can't replicate her visual style without lengthy briefs", "AI tools not refined enough for her aesthetic level"], recent_signals: ["28k IG followers documenting filmmaking", "Recent IG story about AI post-production workflow"] },
  { contact_name: "Kateryna Melnyk", job_title: "Director", company: "Freelance", location: "Kyiv, Ukraine", linkedin_url: "linkedin.com/in/kateryna-melnyk-director", email: "", company_size: "1-10", vertical: "Film & TV", summary: "Freelance director with 4 vertical drama series distributed across European platforms. Has 12k Instagram followers. Teaches vertical drama direction at Kyiv Film School.", fit_score: 77, fit_reason: "Educator + director with community reach — multiplier effect in Kyiv film community.", pain_points: ["Students can't afford professional VFX pipeline", "Self-serve tools needed for low-budget vertical drama productions"], recent_signals: ["Teaches at Kyiv Film School", "Instagram documentary series on vertical drama production"] },
];

export function generateMockLeads(): LeadResult[] {
  return MOCK_LEADS.map((lead, i) => ({
    ...lead,
    id: `lead-mock-${Date.now()}-${i}`,
    source: "ai-agent",
    status: "pending" as const,
  }));
}
