ALTER TABLE public.lead_candidates
  ADD COLUMN IF NOT EXISTS summary text,
  ADD COLUMN IF NOT EXISTS fit_score integer,
  ADD COLUMN IF NOT EXISTS fit_reason text,
  ADD COLUMN IF NOT EXISTS pain_points text[],
  ADD COLUMN IF NOT EXISTS tech_stack text[],
  ADD COLUMN IF NOT EXISTS product_hooks text[],
  ADD COLUMN IF NOT EXISTS champions jsonb,
  ADD COLUMN IF NOT EXISTS recent_signals text[],
  ADD COLUMN IF NOT EXISTS research_depth text DEFAULT 'basic',
  ADD COLUMN IF NOT EXISTS last_enriched_at timestamptz,
  ADD COLUMN IF NOT EXISTS studio_type text,
  ADD COLUMN IF NOT EXISTS website text,
  ADD COLUMN IF NOT EXISTS region text,
  ADD COLUMN IF NOT EXISTS employee_count text,
  ADD COLUMN IF NOT EXISTS funding_stage text,
  ADD COLUMN IF NOT EXISTS location text;